#!/usr/bin/env python3
"""Generate PyDoc HTML and lightweight Markdown documentation for sxLaep."""

from __future__ import annotations

import inspect
import os
import pydoc
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = PROJECT_ROOT / "docs"
PYDOC_DIR = DOCS_DIR / "pydoc"

MODULES = [
    "sxlaep.config",
    "sxlaep.fasta",
    "sxlaep.features",
    "sxlaep.model",
    "sxlaep.training",
    "sxlaep.pipeline",
    "sxlaep.cli",
]


def render_pydoc() -> None:
    """Render PyDoc HTML pages for configured modules."""

    PYDOC_DIR.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(PROJECT_ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    for module in MODULES:
        subprocess.run(
            [sys.executable, "-m", "pydoc", "-w", module],
            cwd=PROJECT_ROOT,
            check=True,
            env=env,
        )
        source_html = PROJECT_ROOT / f"{module}.html"
        target_html = PYDOC_DIR / f"{module}.html"
        if source_html.exists():
            shutil.move(str(source_html), str(target_html))


def write_index() -> None:
    """Write a static HTML index for the generated API pages."""

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    cards = "\n".join(
        f'<div class="card"><a href="pydoc/{m}.html"><code>{m}</code></a><p>{pydoc.describe(pydoc.locate(m))}</p></div>'
        for m in MODULES
    )
    (DOCS_DIR / "index.html").write_text(
        f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>sxLaep API Documentation</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 980px; margin: 40px auto; line-height: 1.55; color: #222; }}
    h1 {{ border-bottom: 2px solid #222; padding-bottom: 10px; }}
    .card {{ border: 1px solid #ddd; border-radius: 10px; padding: 14px 18px; margin: 12px 0; }}
    a {{ color: #0b57d0; text-decoration: none; font-weight: 700; }}
    code {{ background: #f6f8fa; padding: 2px 5px; border-radius: 4px; }}
  </style>
</head>
<body>
  <h1>sxLaep API Documentation</h1>
  <p>Generated with Python PyDoc. The documentation covers FASTA parsing, sequence feature extraction, model training, prediction, and command-line workflows.</p>
  <h2>Modules</h2>
  {cards}
  <h2>Workflow</h2>
  <p>See <a href="WORKFLOW.md">WORKFLOW.md</a> and <a href="API_REFERENCE.md">API_REFERENCE.md</a>.</p>
</body>
</html>
""",
        encoding="utf-8",
    )


def write_api_reference() -> None:
    """Write a Markdown API summary from imported modules."""

    lines = ["# sxLaep API Reference", "", "This file is generated by `scripts/generate_pydoc.py`.", ""]
    for module_name in MODULES:
        module = pydoc.locate(module_name)
        lines.extend([f"## `{module_name}`", "", inspect.getdoc(module) or "No module docstring provided.", ""])
        for name, obj in inspect.getmembers(module):
            if name.startswith("_"):
                continue
            if inspect.isfunction(obj) and getattr(obj, "__module__", "") == module_name:
                signature = str(inspect.signature(obj))
                lines.extend([f"### `{name}{signature}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
            elif inspect.isclass(obj) and getattr(obj, "__module__", "") == module_name:
                lines.extend([f"### class `{name}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
    (DOCS_DIR / "API_REFERENCE.md").write_text("\n".join(lines), encoding="utf-8")


def write_workflow() -> None:
    """Write a concise workflow document."""

    (DOCS_DIR / "WORKFLOW.md").write_text(
        """# sxLaep Workflow

```text
Input FASTA files
    ↓
Read sequences and assign labels
    ↓
Extract multi-property pseudo-AAC, sequence length, CTD, and windowed AAC features
    ↓
Split train/test data
    ↓
Train XGBoost enzyme/non-enzyme classifier
    ↓
Evaluate accuracy, classification report, and confusion matrix
    ↓
Save model, predictions, report, and feature names
```

## Training example

```bash
python scripts/main.py train \
  --noenzyme-fasta data/noenzyme.fasta \
  --enzyme-fasta data/enzyme.fasta \
  --outdir results/raep_training
```

## Prediction example

```bash
python scripts/main.py predict \
  --model results/raep_training/enzyme_xgb_model.ubj \
  --fasta data/query.fasta \
  --output results/query_predictions.csv
```
""",
        encoding="utf-8",
    )


def main() -> None:
    """Generate all documentation assets."""

    sys.path.insert(0, str(PROJECT_ROOT))
    render_pydoc()
    write_index()
    write_api_reference()
    write_workflow()
    print(f"Documentation written to {DOCS_DIR}")


if __name__ == "__main__":
    main()
