#!/usr/bin/env python3
"""Generate PyDoc HTML and lightweight Markdown documentation for sxLaep."""

from __future__ import annotations

import inspect
import os
import pydoc
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = PROJECT_ROOT / "docs"
PYDOC_DIR = DOCS_DIR / "pydoc"

MODULES = [
    "sxlaep.config",
    "sxlaep.fasta",
    "sxlaep.features",
    "sxlaep.model",
    "sxlaep.training",
    "sxlaep.pipeline",
    "sxlaep.cli",
]


def render_pydoc() -> None:
    """Render PyDoc HTML pages for configured modules."""

    PYDOC_DIR.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(PROJECT_ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    for module in MODULES:
        subprocess.run(
            [sys.executable, "-m", "pydoc", "-w", module],
            cwd=PROJECT_ROOT,
            check=True,
            env=env,
        )
        source_html = PROJECT_ROOT / f"{module}.html"
        target_html = PYDOC_DIR / f"{module}.html"
        if source_html.exists():
            shutil.move(str(source_html), str(target_html))


def write_index() -> None:
    """Redirect the legacy project Pages URL to the LabX tools page."""

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "index.html").write_text(
        """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url=https://labxscut.github.io/tools/sxlaep/">
  <link rel="canonical" href="https://labxscut.github.io/tools/sxlaep/">
  <title>sxLaep documentation moved</title>
</head>
<body>
  <p>The sxLaep documentation has moved to
    <a href="https://labxscut.github.io/tools/sxlaep/">https://labxscut.github.io/tools/sxlaep/</a>.
  </p>
  <script>window.location.replace("https://labxscut.github.io/tools/sxlaep/");</script>
</body>
</html>
""",
        encoding="utf-8",
    )


def write_api_reference() -> None:
    """Write a Markdown API summary from imported modules."""

    lines = ["# sxLaep API Reference", "", "This file is generated by `scripts/generate_pydoc.py`.", ""]
    for module_name in MODULES:
        module = pydoc.locate(module_name)
        lines.extend([f"## `{module_name}`", "", inspect.getdoc(module) or "No module docstring provided.", ""])
        for name, obj in inspect.getmembers(module):
            if name.startswith("_"):
                continue
            if inspect.isfunction(obj) and getattr(obj, "__module__", "") == module_name:
                signature = str(inspect.signature(obj))
                lines.extend([f"### `{name}{signature}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
            elif inspect.isclass(obj) and getattr(obj, "__module__", "") == module_name:
                lines.extend([f"### class `{name}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
    (DOCS_DIR / "API_REFERENCE.md").write_text("\n".join(lines), encoding="utf-8")


def write_workflow() -> None:
    """Write a detailed, Manual-style workflow document."""

    # Capture CLI help text from the real argparse parsers so the manual stays accurate.
    # Imported after `sys.path.insert` in `main()`.
    from sxlaep.cli import build_parser  # noqa: WPS433 (runtime import for doc generation)

    parser = build_parser()
    main_help = parser.format_help().rstrip()
    # Argparse does not expose subparsers via a stable public API, but this is acceptable for docs.
    sub = parser._subparsers._group_actions[0]  # type: ignore[attr-defined]
    predict_parser = sub.choices["predict"]
    predict_help = predict_parser.format_help().rstrip()

    (DOCS_DIR / "WORKFLOW.md").write_text(
        f"""# sxLaep Manual

> A detailed, practical, command-line manual for **sxLaep** (enzyme / non-enzyme prediction).
>
> This page is generated by `scripts/generate_pydoc.py` and is intended to be viewed on GitHub (Markdown rendering).

---

## Input Format (FASTA)

`sxlaep` reads protein sequences from a **FASTA** file.

### Minimal FASTA example

```fasta
>seq1 some description
MKVLWALIFLLKSAF
>seq2
GAVLKVLTTGLPALISWIKRKRQQ
```

### Formatting rules

- A FASTA record begins with a header line starting with `>`.
- The **sequence id** is the first token of the header line (before the first whitespace).
- The **description** is the full header line after `>`.
- Sequence lines may wrap; they are concatenated into a single sequence string.

### Newlines / encoding (Windows, WSL, Linux)

Transferring text files among **Windows / WSL / Linux / macOS** may change newline characters and/or encoding.
If you see unexpected parsing errors:

- Re-save the FASTA as **UTF-8**
- Prefer **LF** newlines when working inside WSL

### Recommended quick sanity check (parse-only)

Use the Python API to quickly confirm that your FASTA can be parsed:

```bash
python - <<'PY'
from sxlaep.fasta import read_fasta_records

recs = read_fasta_records("proteins.fasta")
print("records:", len(recs))
print("first_id:", recs[0].identifier)
print("first_len:", len(recs[0].sequence))
PY
```

Notes:
- Non-standard amino acids are sanitized automatically (only the 20 standard amino acids are used).
- Very short sequences (< 10 aa) may yield less reliable predictions.

---

## Computation (sxlaep)

sxLaep provides two command-line styles:

1) **Shorthand**: `sxlaep --input ...` uses the **bundled** model shipped in the installed package.
2) **Subcommand**: `sxlaep predict --model ...` uses a **custom** model file.

### Global usage (`sxlaep --help`)

```text
{main_help}
```

---

## Quick prediction (bundled model) — `sxlaep --input`

This is the simplest and fastest way to run inference with sxLaep.

### Example command

```bash
sxlaep --input proteins.fasta --output predictions.csv
```

### What happens internally

- Loads the bundled model `enzyme_xgb_model.ubj` from the installed `sxlaep` package.
- Extracts alignment-free physicochemical features (fixed configuration for the bundled model).
- Writes a CSV file containing predicted labels and enzyme probabilities.

### Output location

- If `--output` is omitted, the default is `sxlaep_predictions.csv` in the current directory.

### Common mistakes

- **Bundled model not found**: shorthand mode expects a wheel/pip install layout. Install with:
  - `pipx install sxlaep` (recommended), or
  - `pip install sxlaep`
- **Mixing styles**: do not combine `--input/--output` with the `predict` subcommand in the same command.

---

## Prediction with a custom model — `sxlaep predict`

Use this mode if you have your own trained model file.

### Supported model file formats

- Native XGBoost formats: `.ubj`, `.json` (recommended)
- Legacy joblib/pickle formats: `.pkl`, `.joblib` (supported)

### Predict usage (`sxlaep predict --help`)

```text
{predict_help}
```

### Example command (predict)

```bash
sxlaep predict \\
    --model enzyme_xgb_model.ubj \\
    --fasta query.fasta \\
    --output results/query_predictions.csv \\
    --lag 10 \\
    --weight 0.05 \\
    --segments 3 \\
    --add-length \\
    --properties hydro polar charge \\
    --n-jobs 1
```

### Parameter notes (predict)

Feature extraction flags must match training:

- `--lag` (int): maximum correlation lag for pseudo-AAC.
- `--weight` (float): weight for sequence-order correlation terms.
- `--segments` (int): number of N-to-C windows for windowed AAC.
- `--add-length` / `--no-add-length`: append sequence length or not.
- `--properties` (list): one or more of `hydro`, `polar`, `charge`.

Parallelism:

- `--n-jobs` sets the number of worker processes used for feature extraction.

### Detailed option reference (predict)

The following section explains each `sxlaep predict` option in a “manual” style.

#### `--model MODEL`

- **Type**: path
- **Required**: yes
- **Meaning**: the trained model file to load.
- **Supported**:
  - XGBoost native: `.ubj`, `.json` (recommended)
  - Joblib/pickle: `.pkl`, `.joblib`
- **Tip**: prefer native `.ubj`/`.json` for portability and faster loading.

Example:

```bash
sxlaep predict --model enzyme_xgb_model.ubj --fasta query.fasta --output out.csv
```

#### `--fasta FASTA`

- **Type**: path
- **Required**: yes
- **Meaning**: input protein FASTA file.

Example:

```bash
sxlaep predict --model enzyme_xgb_model.ubj --fasta proteins.fasta --output out.csv
```

#### `--output OUTPUT`

- **Type**: path
- **Required**: no
- **Default**: `results/predictions.csv`
- **Meaning**: where to write the output CSV.
- **Note**: the parent directory will be created automatically.

#### `--lag LAG`

- **Type**: integer
- **Default**: `10`
- **Meaning**: maximum correlation lag used by pseudo-AAC.
- **Constraint**: must match training.
- **When to change**: only when you trained the model with a different lag value.

#### `--weight WEIGHT`

- **Type**: float
- **Default**: `0.05`
- **Meaning**: weight applied to sequence-order correlation terms in pseudo-AAC.
- **Constraint**: must match training.

#### `--segments SEGMENTS`

- **Type**: integer
- **Default**: `3`
- **Meaning**: number of N-to-C windows used by windowed AAC.
- **Constraint**: must match training.

#### `--add-length` / `--no-add-length`

- **Type**: flag
- **Default**: enabled (`--add-length`)
- **Meaning**: whether to append raw sequence length to the feature vector.
- **Constraint**: must match training.

#### `--properties [hydro polar charge ...]`

- **Type**: list of tokens
- **Default**: `hydro polar charge`
- **Meaning**: which physicochemical property tables are used by pseudo-AAC.
- **Constraint**: must match training.

Examples:

```bash
# default (explicit)
sxlaep predict --model m.ubj --fasta q.fasta --output out.csv --properties hydro polar charge

# if and only if your model was trained with fewer properties:
sxlaep predict --model m.ubj --fasta q.fasta --output out.csv --properties hydro polar
```

#### `--n-jobs N`

- **Type**: integer
- **Default**: `1`
- **Meaning**: number of parallel workers used for feature extraction.
- **Guideline**:
  - start with `2–4` and scale up
  - set to `1` if you want maximum reproducibility and minimal resource contention

### Shorthand mode notes (`sxlaep --input`)

When using the bundled model shorthand (`--input`), feature parameters are **fixed** (for consistency with the packaged model).  
If you pass feature flags such as `--lag` / `--weight` / `--segments` / `--add-length` / `--properties` together with `--input`, sxLaep will **ignore** them and print a warning.

Recommended patterns:

```bash
# Bundled model (fast screening)
sxlaep --input proteins.fasta --output predictions.csv

# Custom model (fully configurable)
sxlaep predict --model my_model.ubj --fasta proteins.fasta --output predictions.csv --n-jobs 8
```

### Recommended workflows

1) **Screening / gatekeeper** (large metagenomes):
   - run `sxlaep --input ...` to quickly filter out non-enzymes
   - keep high `enzyme_probability` sequences for downstream annotation

2) **Production inference** (fixed model):
   - pin your model file in version control or a released artifact
   - run `sxlaep predict --model ...` with a known parameter set

3) **Batch pipelines**:
   - split huge FASTA inputs
   - run multiple `sxlaep predict` jobs (each with a reasonable `--n-jobs`)
   - merge CSV outputs afterward

---

## Output

Both `sxlaep --input` and `sxlaep predict` write a **CSV**.

### Output columns

| Column | Meaning |
|---|---|
| `sequence_id` | FASTA record id (first token of the header). |
| `description` | Full FASTA header (everything after `>`). |
| `pred_label` | Predicted class (`0` = non-enzyme, `1` = enzyme). |
| `enzyme_probability` | Estimated probability of enzyme class (if the model supports probabilities). |

### CSV example

```csv
sequence_id,description,pred_label,enzyme_probability
seq1,seq1 some description,1,0.9231
seq2,seq2,0,0.1374
```

### Interpreting results

- `pred_label` is the model’s default decision (classification).
- `enzyme_probability` can be used for ranking and thresholding:
  - Sort descending to prioritize likely enzymes.
  - Choose a cutoff based on your tolerance for false positives/negatives.

---

## Speed Up

### Parallel feature extraction (`--n-jobs`)

For large FASTA inputs, feature extraction can dominate runtime. Increase parallel workers:

```bash
sxlaep predict \\
  --model enzyme_xgb_model.ubj \\
  --fasta big.fasta \\
  --output big.csv \\
  --n-jobs 8
```

Guidelines:
- Start with `--n-jobs 2` or `4` and increase gradually.
- Avoid overcommitting CPUs on shared machines.

### Chunking (very large datasets)

For very large datasets (e.g., 100k+ sequences), consider splitting a FASTA into multiple chunks and running multiple `sxlaep` processes, then concatenating CSV outputs.

---

## FAQ / Troubleshooting

### Q1: I get `Bundled model not found ... expected pip/wheel install`

You are likely running from a source checkout without installing the package. Fix:

- Install `sxlaep` (recommended for shorthand mode):
  - `pipx install sxlaep` or `pip install sxlaep`

Then retry:

```bash
sxlaep --input proteins.fasta --output predictions.csv
```

### Q2: My results look wrong with a custom model

Checklist:
- Ensure feature flags match training exactly (`--lag`, `--weight`, `--segments`, `--add-length`, `--properties`).
- Confirm your input is protein FASTA (amino acids), not nucleotides.
- Ensure you are using the same preprocessing choices used during training.

### Q3: FASTA parsing errors or empty sequences

Common causes:
- headers missing the leading `>`
- encoding/newline issues after moving files between Windows and Linux/WSL
- stray invisible characters in sequence lines

Try re-saving as UTF-8 + LF and re-run the sanity check snippet.

### Q4: How do I quickly see all options?

```bash
sxlaep --help
sxlaep predict --help
```
""",
        encoding="utf-8",
    )


def main() -> None:
    """Generate all documentation assets."""

    sys.path.insert(0, str(PROJECT_ROOT))
    render_pydoc()
    write_index()
    write_api_reference()
    write_workflow()
    print(f"Documentation written to {DOCS_DIR}")


if __name__ == "__main__":
    main()
