#!/usr/bin/env python3
"""Generate PyDoc HTML and lightweight Markdown documentation for sxLaep."""

from __future__ import annotations

import inspect
import os
import pydoc
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = PROJECT_ROOT / "docs"
PYDOC_DIR = DOCS_DIR / "pydoc"

MODULES = [
    "sxlaep.config",
    "sxlaep.fasta",
    "sxlaep.features",
    "sxlaep.model",
    "sxlaep.training",
    "sxlaep.pipeline",
    "sxlaep.cli",
]


def render_pydoc() -> None:
    """Render PyDoc HTML pages for configured modules."""

    PYDOC_DIR.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(PROJECT_ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    for module in MODULES:
        subprocess.run(
            [sys.executable, "-m", "pydoc", "-w", module],
            cwd=PROJECT_ROOT,
            check=True,
            env=env,
        )
        source_html = PROJECT_ROOT / f"{module}.html"
        target_html = PYDOC_DIR / f"{module}.html"
        if source_html.exists():
            shutil.move(str(source_html), str(target_html))


def write_index() -> None:
    """Write a static HTML index for the generated API pages."""

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    cards = "\n".join(
        f'<div class="card"><a href="pydoc/{m}.html"><code>{m}</code></a><p>{pydoc.describe(pydoc.locate(m))}</p></div>'
        for m in MODULES
    )
    (DOCS_DIR / "index.html").write_text(
        f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>sxLaep API Documentation</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 980px; margin: 40px auto; line-height: 1.55; color: #222; }}
    h1 {{ border-bottom: 2px solid #222; padding-bottom: 10px; }}
    .card {{ border: 1px solid #ddd; border-radius: 10px; padding: 14px 18px; margin: 12px 0; }}
    a {{ color: #0b57d0; text-decoration: none; font-weight: 700; }}
    code {{ background: #f6f8fa; padding: 2px 5px; border-radius: 4px; }}
  </style>
</head>
<body>
  <h1>sxLaep API Documentation</h1>
  <p>Generated with Python PyDoc. The documentation covers FASTA parsing, sequence feature extraction, model training, prediction, and command-line workflows.</p>
  <h2>Modules</h2>
  {cards}
  <h2>Workflow</h2>
  <p>See <a href="https://github.com/labxscut/sxLaep/blob/dhy/docs/WORKFLOW.md">cmdline workflow manual</a> and <a href="https://github.com/labxscut/sxLaep/blob/dhy/docs/API_REFERENCE.md">API_REFERENCE.md</a>.</p>
</body>
</html>
""",
        encoding="utf-8",
    )


def write_api_reference() -> None:
    """Write a Markdown API summary from imported modules."""

    lines = ["# sxLaep API Reference", "", "This file is generated by `scripts/generate_pydoc.py`.", ""]
    for module_name in MODULES:
        module = pydoc.locate(module_name)
        lines.extend([f"## `{module_name}`", "", inspect.getdoc(module) or "No module docstring provided.", ""])
        for name, obj in inspect.getmembers(module):
            if name.startswith("_"):
                continue
            if inspect.isfunction(obj) and getattr(obj, "__module__", "") == module_name:
                signature = str(inspect.signature(obj))
                lines.extend([f"### `{name}{signature}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
            elif inspect.isclass(obj) and getattr(obj, "__module__", "") == module_name:
                lines.extend([f"### class `{name}`", "", inspect.getdoc(obj) or "No docstring provided.", ""])
    (DOCS_DIR / "API_REFERENCE.md").write_text("\n".join(lines), encoding="utf-8")


def write_workflow() -> None:
    """Write a concise workflow document."""

    (DOCS_DIR / "WORKFLOW.md").write_text(
        """# Command-Line Workflow Examples

## Overview

This page is a practical command-line workflow guide for **sxLaep** (enzyme / non-enzyme prediction).

### Input format (FASTA)

Please make sure your input FASTA is well-formed before running predictions. Transferring text files among macOS, Linux, and Windows may change newline characters and break parsers, so if you see unexpected errors, re-save the file with **UTF-8** encoding and **LF** newlines.

Minimal example:

```fasta
>seq1 some description
MKVLWALIFLLKSAF
>seq2
GAVLKVLTTGLPALISWIKRKRQQ
```

Notes:
- Only the 20 standard amino acids are used; non-standard characters are sanitized automatically.
- Very short sequences (< 10 aa) may yield less reliable predictions.

### Quick prediction (bundled model)

```bash
sxlaep --input proteins.fasta --output predictions.csv
```

This shorthand uses the **bundled model** shipped inside the installed `sxlaep` package (e.g. installed via `pip` / `pipx`).

CLI help:

```text
usage: sxlaep [-h] [-i FASTA] [-o CSV] {predict} ...
```

### Prediction with a custom model (`sxlaep predict`)

If you have your own trained model (native `.ubj`/`.json` or legacy joblib/pickle), use the `predict` subcommand:

```bash
sxlaep predict \\
    --model enzyme_xgb_model.ubj \\
    --fasta query.fasta \\
    --output results/query_predictions.csv \\
    --lag 10 \\
    --weight 0.05 \\
    --segments 3 \\
    --add-length \\
    --properties hydro polar charge \\
    --n-jobs 1
```

**Important:** the feature parameters must match those used during training.

CLI help:

```text
usage: sxlaep predict [-h] --model MODEL --fasta FASTA [--output OUTPUT] ...
```

### Output (CSV)

The output CSV includes identifier columns plus prediction scores:

| Column | Description |
|---|---|
| `sequence_id` | FASTA record id (first token of the header). |
| `description` | Full header line after `>`. |
| `pred_label` | `0` = non-enzyme, `1` = enzyme. |
| `enzyme_probability` | Estimated probability of enzyme class (when available from the model). |

### Speed up (parallel feature extraction)

Use `--n-jobs` in `sxlaep predict` to parallelize feature extraction.

For large-scale runs (10k+ sequences), also consider splitting FASTA files and running multiple `sxlaep predict` processes.

### FAQ / Troubleshooting

- **Bundled model not found**: the shorthand `--input` expects a wheel/pip install layout. Install with `pipx install sxlaep` (recommended) or `pip install sxlaep`.
- **Wrong results / errors after training your own model**: ensure the feature flags (`--lag`, `--weight`, `--segments`, `--add-length`, `--properties`) match training exactly.
- **Input parsing issues**: re-check FASTA formatting and newline style (LF recommended).

### Verifying installation

```bash
sxlaep --help
sxlaep predict --help
```
""",
        encoding="utf-8",
    )


def main() -> None:
    """Generate all documentation assets."""

    sys.path.insert(0, str(PROJECT_ROOT))
    render_pydoc()
    write_index()
    write_api_reference()
    write_workflow()
    print(f"Documentation written to {DOCS_DIR}")


if __name__ == "__main__":
    main()
